// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/swarms": {
    params: {};
  };
  "/api/swarms/:filename": {
    params: {
      "filename": string;
    };
  };
  "/api/agent-templates": {
    params: {};
  };
  "/api/mcp-tools": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/swarms" | "/api/swarms/:filename" | "/api/agent-templates" | "/api/mcp-tools";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.swarms.ts": {
    id: "routes/api.swarms";
    page: "/api/swarms";
  };
  "routes/api.swarms.$filename.ts": {
    id: "routes/api.swarms.$filename";
    page: "/api/swarms/:filename";
  };
  "routes/api.agent-templates.ts": {
    id: "routes/api.agent-templates";
    page: "/api/agent-templates";
  };
  "routes/api.mcp-tools.ts": {
    id: "routes/api.mcp-tools";
    page: "/api/mcp-tools";
  };
};